<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/transitional.dtd">
<!-- Jabbertools Importer web script -->
<!-- (c) 2001 Mike Szczerban <mike@aspect.net> -->
<!--   Jabbertools is released under the GNU GPL version 2.  See http://www.gnu.org for details -->

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html charset=utf-8">
	<title>Jabber roster utility</title>
</head>

<body bgcolor="#ffffff" text="#003366" link="#000000">

<div class="main" align="center">

<h2>Jabber roster utility</h2>

This tool helps with importing existing ICQ/AOL contact lists into your
Jabber roster as well as mass adding/removal of contacts and roster
migration (from one Jabber server to another).

<br />

<a href="jru-help.html">Generic help</a>
<br /><br />How to... <a href="jru-howto.html#import">import ICQ/AIM contact lists</a> - <a href="jru-howto.html#migrates">migrate from one Jabber server to another</a> - <a href="jru-howto.html#migratet">switch contacts from one transport to another</a>

<hr width="75%" noshade="noshade" />
